'CREATE THE ANIMATIONS FOR THE PLAYER SPRITE

IF PLAYER_DYING

        SET_PLAYER_ANIMATION(8, 4,4,4,4)        ' ANIMATION DYING

ELSE IF PLAYER_ON_LADDER AND PLAYER_GOING_UP
        
        SET_PLAYER_ANIMATION(4, 5,6,5,6)        ' ANIMATION UP

ELSE IF PLAYER_ON_LADDER AND PLAYER_GOING_DOWN

        SET_PLAYER_ANIMATION(4, 5,6,5,6)        ' ANIMATION DOWN

ELSE IF PLAYER_ON_LADDER

        SET_PLAYER_ANIMATION(99, 5,5,5,5)        ' ANIMATION DOWN

ELSE IF PLAYER_JUMPING 

        SET_PLAYER_ANIMATION(8, 3,3,3,3)        ' ANIMATION JUMPING

ELSE IF PLAYER_WALKING
        
        SET_PLAYER_ANIMATION(8, 0,1,2,1)        ' ANIMATION WALKING

ELSE
        
        SET_PLAYER_ANIMATION(8, 0,0,0,0)        ' ANIMATION IDLE

END IF