'****************'
'ENEMIES DIE CODE'
'****************'
'ESTE CODIGO SE EJECUTA CUANDO UN ENEMIGO MUERE'

'ASIGNAR ANIMACION AL MORIR'
IF ENEMY_TYPE = 1 THEN                   'PATROLLERS'
    ENEMY_ANIMATION(1,99,2)

ELSEIF ENEMY_TYPE = 2 THEN               'FANTYS'
    ENEMY_ANIMATION(1,99,2)

ELSEIF ENEMY_TYPE = 3 THEN               'JUMPERS'
    ENEMY_ANIMATION(1,99,4)

ELSEIF ENEMY_TYPE = 4 THEN               'OSCILLATORS'
    ENEMY_ANIMATION(1,99,2)

END IF

SCORE_ADD (10)


